apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-frontend
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: sprint-frontend
  template:
    metadata:
      labels:
        app: sprint-frontend
    spec:
      containers:
      - name: sprint-frontend
        image: 571600829776.dkr.ecr.us-east-1.amazonaws.com/sprint-frontend:sprint-frontend-11
        ports:
        - containerPort: 80  # Uygulamanızın dinlediği port
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
